services:
  postgres:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  auth-redis:
    container_name: auth-redis
    image: redis:7.2 # Usamos la imagen oficial de Redis
    restart: always
    volumes:
      - redis_data:/data # Persistimos los datos de Redis
    command: redis-server --appendonly yes # Habilitamos persistencia
    ports:
      - "6379:6379"

volumes:
  redis_data: