import {
  Body,
  Controller,
  Get,
  Param,
  Post,
  Query,
  UseGuards,
} from '@nestjs/common';
import { ApiOperation, ApiTags } from '@nestjs/swagger';
import { JwtAuthGuard } from 'src/common/guards/jwt-auth.guard';
import { CurrentUser } from 'src/common/decorators/current-user.decorator';
import { ClosureService } from './closure.service';
import { CreateClosureDto } from './dto/create-closure.dto';
import { ListClosuresQueryDto } from './dto/list-closures-query.dto';

@ApiTags('closures')
@UseGuards(JwtAuthGuard)
@Controller()
export class ClosureController {
  constructor(private readonly closureService: ClosureService) {}

  @Post('closures')
  @ApiOperation({
    summary: 'Create a financial closure for a household period',
  })
  create(@CurrentUser() userId: string, @Body() dto: CreateClosureDto) {
    return this.closureService.create(userId, dto);
  }

  @Get('households/:householdId/closures')
  @ApiOperation({ summary: 'List closures for a household' })
  findAll(
    @CurrentUser() userId: string,
    @Param('householdId') householdId: string,
    @Query() query: ListClosuresQueryDto,
  ) {
    return this.closureService.findAll(userId, householdId, query);
  }

  @Get('closures/:closureId')
  @ApiOperation({ summary: 'Get closure details and balances' })
  findOne(
    @CurrentUser() userId: string,
    @Param('closureId') closureId: string,
  ) {
    return this.closureService.findOne(userId, closureId);
  }

  @Get('closures/:closureId/balances')
  @ApiOperation({ summary: 'Get final balances generated by a closure' })
  findBalances(
    @CurrentUser() userId: string,
    @Param('closureId') closureId: string,
  ) {
    return this.closureService.findBalances(userId, closureId);
  }

  @Get('closures/:closureId/expenses')
  @ApiOperation({ summary: 'List expenses included in a closure' })
  findExpenses(
    @CurrentUser() userId: string,
    @Param('closureId') closureId: string,
  ) {
    return this.closureService.findExpenses(userId, closureId);
  }
}
